name: Test

on:
  pull_request:
    branches:
      - master
    paths:
      - neo/**

jobs:
  python-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: ./neo/tests.py -v
