name: Test

on:
  pull_request:
    branches:
      - master
    paths:
      - neo/**

jobs:
  python-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: ./neo/tests.py -v

  e2e-test:
    name: Test action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate matrix
        id: neo
        uses: ./
        with:
          pattern: (?P<dir>[^/]+)/
          defaults: true
          ignore-deleted-files: true
          default-patterns: |
            .github/**
      - name: Check output
        run: |
          echo ${{ steps.neo.outputs.matrix }}